web:
  image: nginx:latest
  volumes:
   - ./server.conf:/etc/nginx/conf.d/server.conf
   - ./ssl:/etc/nginx/ssl
   - ../static:/www
  links:
   - serv
  ports:
   - "80:80"
   - "443:443"
  environment:
   - NGINX_HOST=voteoyp.local
   - NGINX_PORT=80
   - NGINX_PORT_SSL=443
   - PROXY_PORT=8080
serv:
  image: node:latest
  working_dir: /www
  volumes:
   - ../:/www/
  ports:
   - "8080:8080"
  environment:
   - NODE_HOST=0.0.0.0
   - NODE_PORT=8080
   - NODE_ENV=production
  command: ["node","index.js"]
